// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace xpp_chatai_vs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCopilotWindowPackageString = "d33fb880-22a0-442d-8408-545cfa9b5a4b";
        public static Guid guidCopilotWindowPackage = new Guid(guidCopilotWindowPackageString);

        public const string guidCopilotWindowPackageCmdSetString = "7e218f19-0efe-4745-8444-a332370604dd";
        public static Guid guidCopilotWindowPackageCmdSet = new Guid(guidCopilotWindowPackageCmdSetString);

        public const string guidPackageMenuSetString = "1041a140-1cb6-44a5-9704-25bd0f8508ca";
        public static Guid guidPackageMenuSet = new Guid(guidPackageMenuSetString);

        public const string guidPackageGroupSetString = "f4a087a7-38ca-4274-a721-dabd07d80721";
        public static Guid guidPackageGroupSet = new Guid(guidPackageGroupSetString);

        public const string guidImagesString = "68e5f899-56c5-4d16-bf9e-d1f6966191bb";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CopilotWindowCommandId = 0x0100;
        public const int Menu = 0x0101;
        public const int Group = 0x0102;
        public const int SecGroup = 0x0103;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}